### ISSUE TITLE
New Effects

### ISSUE THREAD

**Issue by Preetesh21** [smaranjitghose/ArtCV#1]
Can we add a new file which shows a different style of art on the images like stippling effect etc? I would love to contribute towards it.

**Comment by smaranjitghose** [comment]
Nice work @Preetesh21 !

You can build upon this for:
- [ ] Mosaic Art
- [ ] Travelling Salesman Art

Reference: [link](http://dahtah.github.io/imager/stippling.html)

**Comment by Preetesh21** [comment]
> Nice work @Preetesh21 !
> 
> You can build upon this for:
> 
> * [ ]  Mosaic Art
> * [ ]  Travelling Salesman Art
> 
> Reference: [link](http://dahtah.github.io/imager/stippling.html)

Sir I had tried performing the TSP Art for the given image but the results are not very good as I could see.I am attaching the images of the same  here 
This does not use stippling algorithm:
![1](https://user-images.githubusercontent.com/50336851/93660883-02983780-fa71-11ea-9ee8-efed575f7846.png)
This one does:
![end](https://user-images.githubusercontent.com/50336851/93660898-2c515e80-fa71-11ea-9d9e-9d02a0f9dc0e.jpg)

A particular reason which I could think of the result is the low contrast in the image we are using which makes the TSP algorithm lot more straight then we would expect and also on increasing the number of cities in the TSP algorithm beyond 10000 there is a risk of a system crash.

**Comment by Preetesh21** [comment]
Sir, I had tried for the problems and did not get very encouraging results and also the problems took considerably long time(3-4 mins) for solving the backtracking TSP. The result for the same is as :
Without increasing the contrast of the image
![1](https://user-images.githubusercontent.com/50336851/93661355-c4047c00-fa74-11ea-8749-c6581711056a.png)
Increasing the contrast:
![2](https://user-images.githubusercontent.com/50336851/93661361-d2eb2e80-fa74-11ea-9a5d-43e6a268c1eb.png)
I had taken 10000 cities for the kolkata.jpg image , on increasing the number of cities the system crashed.

**Comment by smaranjitghose** [comment]
> Sir, I had tried for the problems and did not get very encouraging results and also the problems took considerably long time(3-4 mins) for solving the backtracking TSP. The result for the same is as :
> Without increasing the contrast of the image
> ![1](https://user-images.githubusercontent.com/50336851/93661355-c4047c00-fa74-11ea-8749-c6581711056a.png)
> Increasing the contrast:
> ![2](https://user-images.githubusercontent.com/50336851/93661361-d2eb2e80-fa74-11ea-9a5d-43e6a268c1eb.png)
> I had taken 10000 cities for the kolkata.jpg image , on increasing the number of cities the system crashed.

I see, have you tried experimentation with  an optimization library like numba

And are you facing difficulties with the mosaic effect too?

**Comment by Preetesh21** [comment]
Yes, sir, I am struggling with both of them :(. The results are not encouraging at all. Sorry.

**Comment by smaranjitghose** [comment]
> Yes, sir, I am struggling with both of them :(. The results are not encouraging at all. Sorry.

No worries. Take your time and try going through some more blogs and research papers. We always do not need pitch perfect results. That's the beauty of art. 

Some quick references: [1](https://towardsdatascience.com/creating-photo-mosaics-using-python-49100e87efc), [2](https://towardsdatascience.com/mosaic-art-using-python-422e9c5c130d)

**Comment by Preetesh21** [comment]
Sure sir.
