### ISSUE TITLE
Foreground Segmentation

### ISSUE THREAD

**Issue by RajS18** [smaranjitghose/ArtCV#16]
Greetings sir,
I observed by the project repository that project aims for Image related manipulations.
I'd love to contribute to the repository.
Please can we add foreground segmentation as well in the option of effects with necessary process libraries like tqdm and OpenCV.
@smaranjitghose Can we please held onto this contribution?

**Comment by smaranjitghose** [comment]
> Greetings sir,
> I observed by the project repository that project aims for Image related manipulations.
> I'd love to contribute to the repository.
> Please can we add foreground segmentation as well in the option of effects with necessary process libraries like tqdm and OpenCV.
> @smaranjitghose Can we please held onto this contribution?

Can you please elaborate more on this

**Comment by RajS18** [comment]
High lighting a particular area in the image and adding onto effects only to the either selected  region (like effects,temp,contrast...) or the non high lighted area (blurring like in portrait image shot via smart phone).

**Comment by smaranjitghose** [comment]
> High lighting a particular area in the image and adding onto effects only to the either selected region (like effects,temp,contrast...) or the non high lighted area (blurring like in portrait image shot via smart phone).

By highlighting I hope you mean separating it into masks. Sure you can go ahead with this. Image Matting is a good application of this

**Comment by RajS18** [comment]
Greetings sir,
Yes it does involve image matting.
Please can you have a look on the unreviewed PR (Cartoon effect) as well ?
And Please attach "Hacktoberfest" label on this issue.
Thank you. 😊
