### ISSUE TITLE
Image Enhancer

### ISSUE THREAD

**Issue by RajS18** [smaranjitghose/ArtCV#17]
Greetings sir,
I observed by the project repository that project aims for Image related manipulations.
I'd love to contribute to the repository.
Please we add Image enhancing option with gamma correction as 1 option for contribution @smaranjitghose ?

**Comment by smaranjitghose** [comment]
> Greetings sir,
> I observed by the project repository that project aims for Image related manipulations.
> I'd love to contribute to the repository.
> Please we add Image enhancing option with gamma correction as 1 option for contribution @smaranjitghose ?

I wanted to add image enhancements like DeHazing, Image SuperResolution as well...ah..Gamma Correction works nicely for a lot of cases too, I think when we develop the streamlit app, we need to put a slider for the gamma value
