### ISSUE TITLE
Vintage Anime Effect

### ISSUE THREAD

**Issue by RajS18** [smaranjitghose/ArtCV#22]
Greetings sir,
I observed by the project repository that project aims for Image related manipulations.
I'd love to contribute to the repository.
Please can we add the anime effect as well in the option of effects with necessary process libraries.
@smaranjitghose Can we please held onto this contribution?

**Comment by smaranjitghose** [comment]
> Greetings sir,
> I observed by the project repository that project aims for Image related manipulations.
> I'd love to contribute to the repository.
> Please can we add the anime effect as well in the option of effects with necessary process libraries.
> @smaranjitghose Can we please held onto this contribution?

Sure. That would be nice!

**Comment by RajS18** [comment]
Greetings sir,
Please can you have a look on the unreviewed PR (Cartoon effect) as well ?
And Please attach "Hacktoberfest" label on this issue.
Thank you. 😊

**Comment by carrycooldude** [comment]
Sir Can you elaborate on this issue @smaranjitghose
