### ISSUE TITLE
Sobel Edge detection without OpenCV 

### ISSUE THREAD

**Issue by Namyalg** [smaranjitghose/ArtCV#24]
This script can be used to perform Sobel Edge Detection on images without the use of OpenCV inbuilt functions

**Comment by Namyalg** [comment]
@smaranjitghose , please assign this issue, I would like to make a contribution toward Hacktoberfest

**Comment by Namyalg** [comment]
Yes, I will do that

**Comment by smaranjitghose** [comment]
Additionally, feel free to give a PR for the Sobel edge detection [without open-cv] script. In the later stages when we build our web app for this project, we can have a dedicated page for Edge Detection like Sobel Edge Detection, Canny Edge Detection, Holistically Nested Edge Detection, CASENet, Dynamic Feature Fusion for Semantic Edge Detection, Richer Convolutional Features for Edge Detection, DexiNed,etc

**Comment by Namyalg** [comment]
Sure, I will create a PR for Sobel Edge detection without Open CV

**Comment by Namyalg** [comment]
There are many other kernels that can be used for edge detection like the Sobel kernels, like the Prewitt, Scharr etc, so do these need separate PR's or will a single script suffice?

**Comment by smaranjitghose** [comment]
> There are many other kernels that can be used for edge detection like the Sobel kernels, like the Prewitt, Scharr etc, so do these need separate PR's or will a single script suffice?

We can make this more manageable by making an ```edge_detection.py``` script which takes in the path of the image, a string (say HED for holistically nested edge detection) and uses a block of if-else statements to perform the desired operation.  We can declare each of the edge detection filters in separate files and import them into this script.

I am suggesting this because later when we turn this project into a python package it will be really managable.

**Comment by Namyalg** [comment]
Okay!

**Comment by Purvanshsingh** [comment]
Hey @smaranjitghose ,
can you assign me this issue I want to work on it?

**Comment by Purvanshsingh** [comment]
@smaranjitghose why this issue is closed?

**Comment by smaranjitghose** [comment]
> @smaranjitghose why this issue is closed?

There was no contribution for this since last assigned. Hence we are closing all inactive issues and raising new ones as per an update plan

**Comment by Purvanshsingh** [comment]
I am a participant in SWOC our contribution started yesterday only.
