### ISSUE TITLE
Emboss Effect

### ISSUE THREAD

**Issue by RajS18** [smaranjitghose/ArtCV#29]
Greetings sir,

Please can we add the emboss effect as well in the option of effects with necessary process libraries like tqdm and OpenCV.
This effect is helps in protruded/sunken effects on the image's edges (Especially useful for Texts) but gives extra ordinary results on images.
@smaranjitghose Can we please held onto this contribution?

**Comment by smaranjitghose** [comment]
> Greetings sir,
> 
> Please can we add the emboss effect as well in the option of effects with necessary process libraries like tqdm and OpenCV.
> This effect is helps in protruded/sunken effects on the image's edges (Especially useful for Texts) but gives extra ordinary results on images.
> @smaranjitghose Can we please held onto this contribution?

That's a fantastic idea. I am curious to see how you are thinking of implementing it
