### ISSUE TITLE
Adding Progress Bars

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#3]
While some of the effects are relatively simpler to produce, others require some amount of time mathematical computation. We can make use of progress bars in the terminal to give the user a visual insight of how much of the process is done. The tqdm library can be used for this

**Comment by hpnightowl** [comment]
i want to try on this issue if still open as a part of SWOC? adding progress bar to the model computation so basically we need normal progress bars or the color once?

**Comment by smaranjitghose** [comment]
> i want to try on this issue if still open as a part of SWOC? adding progress bar to the model computation so basically we need normal progress bars or the color once?

Yes. All issues are open to everyone
- Basically the progress bars are for showing how much time is left for the operation (let's say neural style to complete). We eventually want to build this as a python package

**Comment by Aayush-hub** [comment]
@smaranjitghose Can I work on this? #SWOC
