### ISSUE TITLE
Motion Blur 

### ISSUE THREAD

**Issue by RajS18** [smaranjitghose/ArtCV#32]
Greetings sir,

Please can we add the Motion Blur effect as well in the option of effects with necessary process libraries like tqdm and OpenCV.
This effect is helps in demonstrating the blur effect observed by the camera on calibrating and clicking pictures in high speeds (generally observed and useful in designing computer games). This effect can be demonstrated in any direction specified. (I'd go for the most common ones like horizontal and diagonal).
@smaranjitghose Can we please held onto this contribution?

**Comment by RajS18** [comment]
Sir please can you attach "hacktoberfest_accepted" label onto this issue. I'm not sure what it does but still.

**Comment by khodwe56** [comment]
@smaranjitghose #SWOC Interested in this.

**Comment by Aayush-hub** [comment]
@smaranjitghose  I want to work on this, can you please assign me this? #SWOC

**Comment by smaranjitghose** [comment]
Already done. If you have any deep learning based (GANs) alternative do raise an issue
