### ISSUE TITLE
Splash effect (Color filtering)

### ISSUE THREAD

**Issue by RajS18** [smaranjitghose/ArtCV#33]
Greetings sir,

Please can we add the Splash effect (color specific) as well in the option of effects with necessary process libraries like tqdm and OpenCV.
This effect is helps highlighting a specific color region in the image an is used especially by the VFX artists to add CGI in image frames in a video and gives extra ordinary results on images.
@smaranjitghose Can we please held onto this contribution?

**Comment by RajS18** [comment]
Sir please can you attach "hacktoberfest_accepted" label onto this issue. I'm not sure what it does but still.

**Comment by smaranjitghose** [comment]
> Sir please can you attach "hacktoberfest_accepted" label onto this issue. I'm not sure what it does but still.

Sure. Don't worry. I would eventually label the PR and the repo has the topic set for being a hacktoberfest2020 opted in repo
