### ISSUE TITLE
Suggest/Request the addition of New Effect - ASCII Art on Image + Video

### ISSUE THREAD

**Issue by aryashah2k** [smaranjitghose/ArtCV#40]
Dear sir, @smaranjitghose , I have been working on ASCII Art as part of my pet project and would love to see make it to a part of this repository as an individual project. I am using OpenCV for the same. 
Could you consider adding this art form into your existing list of projects. I am aiming to enhance and work on it during my time at DWOC or SWOC 
Also I wish to challenge myself by working on Video input for real time ascii conversion as a secondary part once I successfully merge the repo with Ascii art for image.
I'm willing to create a detailed documentation also for the same!
Waiting for your reply.  You may close the issue once acknowledged and assigned.
Thanks!

**Comment by smaranjitghose** [comment]
> Dear sir, @smaranjitghose , I have been working on ASCII Art as part of my pet project and would love to see make it to a part of this repository as an individual project. I am using OpenCV for the same.
> Could you consider adding this art form into your existing list of projects. I am aiming to enhance and work on it during my time at DWOC or SWOC
> Also I wish to challenge myself by working on Video input for real time ascii conversion as a secondary part once I successfully merge the repo with Ascii art for image.
> I'm willing to create a detailed documentation also for the same!
> Waiting for your reply. You may close the issue once acknowledged and assigned.
> Thanks!

Sure! Looking forward to see your algorithm!

**Comment by aryashah2k** [comment]
Hi there @smaranjitghose , could you add this issue under the SWOC Label for contribution?

**Comment by aryashah2k** [comment]
Dear @smaranjitghose , Ascii Art For Image Pull Request Has Been created!

Reference: https://github.com/smaranjitghose/ArtCV/pull/50
