### ISSUE TITLE
Query regarding addition of deep learning based image transformations

### ISSUE THREAD

**Issue by C3Suryansu** [smaranjitghose/ArtCV#41]
Dear Sir, @smaranjitghose 
I wanted to know whether can we add deep learning based image transformations, like those done by StyleGANs or such, to create interesting results on various images. An example of such an image transformation based on the image given in the readme could be seen below, 
![image](https://user-images.githubusercontent.com/39475196/103222988-4a214000-494b-11eb-9f7d-ced43ce378cf.png)
The art style is that of  Wassily Kandinsky, and such results could be obtained by various implementations of StyleGANs. With your permission I would like to work on the same and contribute the code related to acquiring such results.

I was trying out such models and intend to implement them and contribute to open source via the DWOC programme.

**Comment by smaranjitghose** [comment]
> Dear Sir, @smaranjitghose
> I wanted to know whether can we add deep learning based image transformations, like those done by StyleGANs or such, to create interesting results on various images. An example of such an image transformation based on the image given in the readme could be seen below,
> ![image](https://user-images.githubusercontent.com/39475196/103222988-4a214000-494b-11eb-9f7d-ced43ce378cf.png)
> The art style is that of Wassily Kandinsky, and such results could be obtained by various implementations of StyleGANs. With your permission I would like to work on the same and contribute the code related to acquiring such results.
> 
> I was trying out such models and intend to implement them and contribute to open source via the DWOC programme.

Wow! I didn't expect much of the participants to be interested in GANs let alone StyleGAN. Sure, I am looking forward to your contributions @C3Suryansu

**Comment by smaranjitghose** [comment]
Any updates @C3Suryansu . It's been almost 3 weeks

**Comment by C3Suryansu** [comment]
Extremely sorry sir, I have been busy with college exams and work, hence been unable to work and submit the code for the same. I shall make a PR regarding this within few days.

**Comment by smaranjitghose** [comment]
> Extremely sorry sir, I have been busy with college exams and work, hence been unable to work and submit the code for the same. I shall make a PR regarding this within few days.

I totally understand your position being a senior year undergrad myself. Just let me know if you are busy from next time onwards so that I am aware you are willing to continue with this issue meanwhile I let others try😊

**Comment by C3Suryansu** [comment]
Hello sir, I don't think I will be able to work on this before February first week due to semester exams. Please go ahead with assigning this issue to others. Really sorry for this.

**Comment by Bhagyashri2000** [comment]
I would like to work on this issue. I am DWoC participant. @smaranjitghose can you please assign this to me?

**Comment by smaranjitghose** [comment]
> I would like to work on this issue. I am DWoC participant. @smaranjitghose can you please assign this to me?

This is just a discussion issue. If you know how to use StyleGan2 raise a new PR for it

**Comment by smaranjitghose** [comment]
> Hello sir, I don't think I will be able to work on this before February first week due to semester exams. Please go ahead with assigning this issue to others. Really sorry for this.

Its' fine. I can understand
