### ISSUE TITLE
Gamma correction - Power law transformation

### ISSUE THREAD

**Issue by hritik5102** [smaranjitghose/ArtCV#44]
Hello @smaranjitghose, I wanted to add an implementation of gamma correction using OpenCV in this repository, please assign me this issue for **SWOC2021**.

Please also labels this issue **_SWOC2021_** and **_SWOC_**. 
Thank you :)

**Comment by smaranjitghose** [comment]
> Hello @smaranjitghose, I wanted to add an implementation of gamma correction using OpenCV in this repository, please assign me this issue for **SWOC2021**.
> 
> Please also labels this issue **_SWOC2021_** and **_SWOC_**.
> Thank you :)

Gamma Correction is not an actual artistic effect. It helps in image enhancement which does not conform with the goals of this project
