### ISSUE TITLE
Colorize Black and White Images

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#57]

**Comment by pravallika-1305** [comment]
Hey @smaranjitghose!
I would like to work on this issue as a part of SWOC, I plan on building a CNN using TensorFlow2 & Keras for doing so...

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose!
> I would like to work on this issue as a part of SWOC, I plan on building a CNN using TensorFlow2 & Keras for doing so...

I have not used a direct CNN approach for this but definitely would love to see your input

**Comment by smaranjitghose** [comment]
> > Hey @smaranjitghose!
> > I would like to work on this issue as a part of SWOC, I plan on building a CNN using TensorFlow2 & Keras for doing so...
> 
> I have not used a direct CNN approach for this but definitely would love to see your input

I am assigning this to you for next 4 days. Cool? @pravallika-1305

**Comment by pravallika-1305** [comment]
sure!

**Comment by pravallika-1305** [comment]
hey! I need another day fr this...

**Comment by smaranjitghose** [comment]
> hey! I need another day fr this...

Cool, I am giving you 3 more days. I hope that will be sufficient for the first PR
