### ISSUE TITLE
Artistic Style Transfer

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#59]
Reference: [Fast Style Transfer](https://github.com/lengstrom/fast-style-transfer)

**Comment by sagnik1511** [comment]
Hello @smaranjitghose  I also want to contribute into this issue #59 as I have not opted  any other issue recently.Please assign me.

**Comment by BlueBlaze6335** [comment]
Hello @smaranjitghose , I want to work on this issue. Can you please assign this to me ?!

**Comment by smaranjitghose** [comment]
> Hello @smaranjitghose I also want to contribute into this issue #59 as I have not opted any other issue recently.Please assign me.

Assigned for 3 days.
I would prefer if you use tensorflow 2.3+

**Comment by smaranjitghose** [comment]
> Hello @smaranjitghose , I want to work on this issue. Can you please assign this to me ?!

After @sagnik1511 's deadline, you can take over

**Comment by sagnik1511** [comment]
> > Hello @smaranjitghose I also want to contribute into this issue #59 as I have not opted any other issue recently.Please assign me.
> 
> Assigned for 3 days.
> I would prefer if you use tensorflow 2.3+

Okay . I'll try with tensorflow 2
