### ISSUE TITLE
Photorealistic Style Transfer

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#60]
[Reference](https://arxiv.org/abs/1912.02398?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A+arxiv%252FQSXk+%2528ExcitingAds%2521+cs+updates+on+arXiv.org%2529)

**Comment by sagnik1511** [comment]
I want to resolve this issue #60. Please assign this to me.

**Comment by smaranjitghose** [comment]
> I want to resolve this issue #60. Please assign this to me.

Assigned for 5 days

**Comment by sagnik1511** [comment]
Is it okay??? 
https://github.com/sagnik1511/Style-Transfer-using-VGG-verydeep-19  
please review this.
after that I'm going to create the PR.
