### ISSUE TITLE
Implement Holistically Nested Edge Detection

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#62]

**Comment by simarpreetsingh-019** [comment]
Hey @smaranjitghose , could you explain a bit about this issue? And is it valid to be put in DWOC category also?
I want to know whether this implementation is for images, videos that are saved, or for real time purpose use?

**Comment by smaranjitghose** [comment]
> Hey @smaranjitghose , could you explain a bit about this issue? And is it valid to be put in DWOC category also?
> I want to know whether this implementation is for images, videos that are saved, or for real time purpose use?

This is currently for images. Yes it's valid under DWOC. However extending it to videos is not a big deal once the base implementation is complete

**Comment by lokeshvenkatesan** [comment]
Hello @smaranjitghose ,  Assign me this task. Thank you.

**Comment by simarpreetsingh-019** [comment]
> > Hey @smaranjitghose , could you explain a bit about this issue? And is it valid to be put in DWOC category also?
> > I want to know whether this implementation is for images, videos that are saved, or for real time purpose use?
> 
> This is currently for images. Yes it's valid under DWOC. However extending it to videos is not a big deal once the base implementation is complete

@smaranjitghose, I had some issues with my laptop and papers are going on, that's why it had taken some time, I am still working on it, will be pushing it asap.
