### ISSUE TITLE
Rearrange the scripts in the form of a module

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#63]

**Comment by vaishnavi-1** [comment]
@smaranjitghose Can you elaborate a little bit about this issue? Means do you mean that we have to make a folder and then add all the scripts in that?

**Comment by SinghShreya05** [comment]
@smaranjitghose I'll like to work on this, kindly assign this to me.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Can you elaborate a little bit about this issue? Means do you mean that we have to make a folder and then add all the scripts in that?

Please check out how to build python modules and libraries
