### ISSUE TITLE
Mosaic Effect

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#7]

**Comment by aryashah2k** [comment]
Hello sir, @smaranjitghose , I am really interested in trying to implement code for Mosaic Effect using OpenCV as part of my contributions during DWOC or SWOC . You can assign this issue to me. 
Also, should I work on this effect from the point of view of an image, or do I need to create a script that works on video? Please let me know!
I'm willing to create a detailed documentation also for the same!

**Comment by smaranjitghose** [comment]
> Hello sir, @smaranjitghose , I am really interested in trying to implement code for Mosaic Effect using OpenCV as part of my contributions during DWOC or SWOC . You can assign this issue to me.
> Also, should I work on this effect from the point of view of an image, or do I need to create a script that works on video? Please let me know!
> I'm willing to create a detailed documentation also for the same!

For the v.1.0,0 we are just doing it for the images. 
However, if you are interested you can create a separate function for the video in the same script

**Comment by aryashah2k** [comment]
Okay sir, I shall start from an image point of view and then once I finish with this issue I shall open a new one for video if it is feasible for me! Thanks for assigning this to me. Won't disappoint you!

**Comment by aryashah2k** [comment]
Hi there @smaranjitghose , could you add this issue under the SWOC Label for contribution?

**Comment by smaranjitghose** [comment]
> Hi there @smaranjitghose , could you add this issue under the SWOC Label for contribution?

Sure

**Comment by aryashah2k** [comment]
@smaranjitghose , the mosaic script issue has been successfully merged . This issue can be successfully closed :)
