### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by PinRathod** [smaranjitghose/ArtCV#78]
Code of conduct file which is important for the open source project community.
Can I work on this for DWoC?

**Comment by anirudhsai20** [comment]
Hi @smaranjitghose . Can I please work on this under DWOC or SWOC?

**Comment by PinRathod** [comment]
@smaranjitghose assign it to me.

**Comment by smaranjitghose** [comment]
NOT REQUIRED
