### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by PinRathod** [smaranjitghose/ArtCV#79]
Add contributing.md file for guiding how to contributing open source project.
Can I work on this for DWoC?

**Comment by PinRathod** [comment]
@smaranjitghose can I work on

**Comment by PinRathod** [comment]
@smaranjitghose can I work on this?

**Comment by smaranjitghose** [comment]
No.
Unless some major content improvements are required, these are purely intended for maintainers
