### ISSUE TITLE
Streamlit App

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#8]
- Use [this](https://github.com/smaranjitghose/img_ai_app_boilerplate) template to set up a streamlit app and push it a ```test``` branch

**Comment by ThenoobMario** [comment]
Hey If you don't mind I can work on this :P

**Comment by smaranjitghose** [comment]
Sure

**Comment by ThenoobMario** [comment]
Hey @smaranjitghose , how do I push it into a test branch on your repo?

**Comment by smaranjitghose** [comment]
While creating a PR, compare it with the test branch instead of the master

**Comment by ThenoobMario** [comment]
Okay

**Comment by ThenoobMario** [comment]
Also, I tried to squash the commits but wasn't able to do it :/

**Comment by ThenoobMario** [comment]
Also if you could help me understand the differences in **sobel_filter.py** and **canny_edge_detection.py**. They both have similar code I feel

**Comment by ThenoobMario** [comment]
> Also if you could help me understand the differences in **sobel_filter.py** and **canny_edge_detection.py**. They both have similar code I feel

@smaranjitghose ?
