### ISSUE TITLE
Neural Style Transfer

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/ArtCV#9]
Before giving a PR, please have a look at the guidelines given [here](https://github.com/smaranjitghose/auto_vaidya)

**Comment by hershd23** [comment]
Hi I guess this is already available in the Pytorch docs. 
https://pytorch.org/tutorials/advanced/neural_style_tutorial.html

I can add this to the repository for you, as part of Hacktoberfest. You can assign me this issue

**Comment by smaranjitghose** [comment]
> Hi I guess this is already available in the Pytorch docs.
> https://pytorch.org/tutorials/advanced/neural_style_tutorial.html

> I can add this to the repository for you, as part of Hacktoberfest. You can assign me this issue

Yes, I am aware of that 😅. For this issue, I would prefer having models saved for some custom styles rather than training the model every time we run the script. Have a look at [Adrian's](https://www.pyimagesearch.com/2018/08/27/neural-style-transfer-with-opencv/) blog for reference

**Comment by hershd23** [comment]
The blog seems pretty cool. I am still interested in this issue. The can follow the blog to create the PR initially and then we can take it from there and add more styles etc. Sounds Good?

**Comment by smaranjitghose** [comment]
> The blog seems pretty cool. I am still interested in this issue. The can follow the blog to create the PR initially and then we can take it from there and add more styles etc. Sounds Good?

Sure you can add those styles but I would prefer you to train them scratch in PyTorch or TF 2.0

**Comment by hershd23** [comment]
Cool!

**Comment by khodwe56** [comment]
Respected Sir, @smaranjitghose  #SWOC Interested in this.Can do this.

**Comment by smaranjitghose** [comment]
> Respected Sir, @smaranjitghose #SWOC Interested in this.Can do this.

Sure. Please comment [here](https://github.com/smaranjitghose/ArtCV/issues/43)
